apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: reservation
  name: reservation
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8087
      targetPort: 8087
  selector:
    app: reservation
status:
  loadBalancer: {}
